import type { ProjectRecord } from "@/types/project";

const mockProjectSeed: ProjectRecord = {
  id: "project-fcp-inspired",
  name: "Brand Story Rough Cut",
  location: "/projects/brand-story",
  version: "0.1.0",
  notes: "使用真实媒体文件：video-a.mp4（9s）、video-b.mp4（4.3s）、voice-a.m4a（7s）。",
  mediaItems: [
    {
      id: "media-video-a",
      name: "video-a.mp4",
      type: "video",
      importMode: "copied",
      originalPath: "/media/video-a.mp4",
      projectPath: "media/video-a.mp4",
      durationInFrames: 269,
      sourceLabel: "视频片段 A",
      createdAt: "2026-04-20T09:15:00",
      updatedAt: "2026-04-22T08:10:00",
      fileSize: 18_540_032,
    },
    {
      id: "media-video-b",
      name: "video-b.mp4",
      type: "video",
      importMode: "copied",
      originalPath: "/media/video-b.mp4",
      projectPath: "media/video-b.mp4",
      durationInFrames: 128,
      sourceLabel: "视频片段 B",
      createdAt: "2026-04-20T09:16:42",
      updatedAt: "2026-04-20T09:16:42",
      fileSize: 8_912_384,
    },
    {
      id: "media-audio-voice",
      name: "voice-a.m4a",
      type: "audio",
      importMode: "copied",
      originalPath: "/media/voice-a.m4a",
      projectPath: "media/voice-a.m4a",
      durationInFrames: 211,
      sourceLabel: "语音配音",
      createdAt: "2026-04-21T14:03:10",
      updatedAt: "2026-04-21T14:03:10",
      fileSize: 1_245_184,
    },
  ],
  timeline: {
    fps: 30,
    width: 1920,
    height: 1080,
    durationInFrames: 420,
    videoTracks: [
      {
        id: "track-video-primary",
        name: "主视频轨",
        type: "video",
        clips: [
          {
            id: "clip-video-a",
            mediaId: "media-video-a",
            title: "Video A",
            startFrame: 0,
            durationInFrames: 269,
            sourceIn: 0,
            color: "#f97316",
            sourceType: "imported-video",
          },
          {
            id: "clip-video-b",
            mediaId: "media-video-b",
            title: "Video B",
            startFrame: 269,
            durationInFrames: 128,
            sourceIn: 0,
            color: "#0f766e",
            sourceType: "imported-video",
          },
        ],
      },
    ],
    audioTracks: [
      {
        id: "track-audio-voice",
        name: "语音轨",
        type: "audio",
        clips: [
          {
            id: "clip-audio-voice",
            mediaId: "media-audio-voice",
            title: "Voice Over",
            startFrame: 0,
            durationInFrames: 211,
            sourceIn: 0,
            color: "#d97706",
            sourceType: "extracted-audio",
          },
        ],
      },
    ],
  },
  importTasks: [
    {
      id: "import-video-a",
      sourceName: "video-a.mp4",
      mode: "copied",
      status: "completed",
      importedAt: "2026-04-22 10:12",
      notes: "已导入主视频轨。",
      output: {
        videoClips: 1,
        audioClips: 0,
        captions: 0,
      },
    },
    {
      id: "import-video-b",
      sourceName: "video-b.mp4",
      mode: "copied",
      status: "completed",
      importedAt: "2026-04-22 10:15",
      notes: "已导入第二视频片段。",
      output: {
        videoClips: 1,
        audioClips: 0,
        captions: 0,
      },
    },
    {
      id: "import-voice-a",
      sourceName: "voice-a.m4a",
      mode: "copied",
      status: "completed",
      importedAt: "2026-04-22 10:18",
      notes: "已导入语音配音。",
      output: {
        videoClips: 0,
        audioClips: 1,
        captions: 0,
      },
    },
  ],
  analysis: {
    overallSummary:
      "当前项目包含 2 段视频片段和 1 段语音配音，总时长约 14 秒。视频 A 约 9 秒，视频 B 约 4.3 秒，语音约 7 秒。",
    sceneCount: 2,
    transcriptCount: 3,
    detectedFillerWordCount: 0,
    keyframes: [
      {
        id: "kf-1",
        label: "Video A 开场",
        description: "视频片段 A 的前 4 秒。",
        startFrame: 0,
        endFrame: 120,
        color: "#f97316",
      },
      {
        id: "kf-2",
        label: "Video A 后段",
        description: "视频片段 A 的后半段。",
        startFrame: 120,
        endFrame: 269,
        color: "#ea580c",
      },
      {
        id: "kf-3",
        label: "Video B",
        description: "视频片段 B，约 4.3 秒。",
        startFrame: 269,
        endFrame: 397,
        color: "#0f766e",
      },
    ],
    transcriptSegments: [
      {
        id: "seg-1",
        speaker: "Speaker A",
        startFrame: 0,
        endFrame: 70,
        text: "第一段语音内容。",
        fillerWords: [],
      },
      {
        id: "seg-2",
        speaker: "Speaker A",
        startFrame: 70,
        endFrame: 140,
        text: "第二段语音内容。",
        fillerWords: [],
      },
      {
        id: "seg-3",
        speaker: "Speaker A",
        startFrame: 140,
        endFrame: 211,
        text: "第三段语音内容。",
        fillerWords: [],
      },
    ],
    editSuggestions: [
      {
        id: "edit-1",
        title: "调整语音与视频对齐",
        source: "ai-tags",
        action: "trim",
        confidence: 0.85,
        affectedClipIds: ["clip-video-a", "clip-audio-voice"],
        description:
          "语音配音（211f）结束早于视频 A（269f），可考虑在 211f 后剪短视频或补充音乐。",
      },
      {
        id: "edit-2",
        title: "视频 B 接续",
        source: "ai-tags",
        action: "insert-broll",
        confidence: 0.8,
        affectedClipIds: ["clip-video-b"],
        description: "视频片段 B 作为接续素材，在 269f 处与视频 A 无缝衔接。",
      },
    ],
  },
  voiceProfiles: [
    {
      id: "voice-brand-host",
      name: "Brand Host",
      source: "uploaded",
      description: "上传样本建立的品牌旁白音色，适合正式讲述段。",
      previewLabel: "稳重 / 温和 / 清晰",
      isDefault: true,
    },
    {
      id: "voice-scratch-read",
      name: "Scratch Read",
      source: "recorded",
      description: "录音样本生成的临时音色，适合快速出粗剪旁白。",
      previewLabel: "直接 / 中性 / 快速",
      isDefault: false,
    },
  ],
  ttsJobs: [],
};

export function createMockProject(): ProjectRecord {
  return structuredClone(mockProjectSeed);
}

export const mockRecentProjects = [
  {
    id: "recent-1",
    name: "Brand Story Rough Cut",
    location: "/projects/brand-story",
    summary: "2 段视频 + 1 段语音的样例项目",
  },
  {
    id: "recent-2",
    name: "Podcast Snippets",
    location: "/projects/podcast-snippets",
    summary: "字幕驱动剪辑实验项目",
  },
];
