import type { DependencyItem, ModelConfig } from "@/types/settings";

export const mockModelConfigs: ModelConfig[] = [
  {
    id: "model-vl-primary",
    category: "vl",
    name: "Vision Analysis API",
    provider: "OpenAI-compatible VL",
    endpoint: "https://vl.example.com/v1/chat/completions",
    apiKey: "sk-vl-demo",
    helpTitle: "VL 接入说明",
    helpUrl: "https://remotion.dev/docs",
    description: "用于关键帧画面分析与场景标签输出，当前只保留 API 地址与 key 配置。",
    status: "configured",
  },
  {
    id: "model-llm-primary",
    category: "llm",
    name: "Editing Decision API",
    provider: "OpenAI-compatible LLM",
    endpoint: "https://llm.example.com/v1/chat/completions",
    apiKey: "sk-llm-demo",
    helpTitle: "LLM 剪辑说明",
    helpUrl: "https://platform.openai.com/docs",
    description: "接收结构化分析结果并返回剪辑候选，当前不在前端定义最终协议。",
    status: "configured",
  },
  {
    id: "model-audio-stt",
    category: "audio",
    name: "Speech To Text API",
    provider: "Whisper-compatible",
    endpoint: "https://stt.example.com/v1/audio/transcriptions",
    apiKey: "sk-stt-demo",
    helpTitle: "音频转写说明",
    helpUrl: "https://platform.openai.com/docs/guides/speech-to-text",
    description: "用于视频抽音频转文字、单片段补转录和 transcript 生成。",
    status: "ready",
    lastCheckedAt: "2026-04-22 11:56",
  },
  {
    id: "model-tts-primary",
    category: "tts",
    name: "TTS Synthesis API",
    provider: "IndexTTS-compatible",
    endpoint: "https://tts.example.com/v1/tts",
    apiKey: "sk-tts-demo",
    helpTitle: "TTS 接入说明",
    helpUrl: "https://platform.openai.com/docs/guides/text-to-speech",
    description: "用于文本转语音、试听和插入时间轴，当前只做 API 接入配置。",
    status: "ready",
    lastCheckedAt: "2026-04-22 11:58",
  },
];

export const mockDependencies: DependencyItem[] = [
  {
    id: "dep-ffmpeg",
    name: "ffmpeg",
    type: "system",
    status: "installed",
    version: "7.1",
    installHint: "brew install ffmpeg",
    notes: "用于媒体转码、抽帧、抽音频和最终导出。",
  },
  {
    id: "dep-ffprobe",
    name: "ffprobe",
    type: "system",
    status: "installed",
    version: "7.1",
    installHint: "随 ffmpeg 一起安装",
    notes: "用于读取视频时长和媒体元信息。",
  },
  {
    id: "dep-python",
    name: "Python Runtime",
    type: "python-runtime",
    status: "warning",
    version: "3.11",
    installHint: "uv python install 3.11",
    notes: "当前前端只展示状态，后续依赖 Python 工作流和本地服务。",
  },
  {
    id: "dep-funasr",
    name: "funasr",
    type: "python-package",
    status: "missing",
    installHint: "uv pip install funasr",
    notes: "若后续仍保留本地音频转写链路，则需要此包。",
  },
  {
    id: "dep-remotion",
    name: "Remotion Tooling",
    type: "python-package",
    status: "installed",
    version: "4.0.448",
    installHint: "npm install remotion @remotion/player",
    notes: "当前前端编辑核心已经围绕 Remotion 建立。",
  },
];
